AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python_runtime_upgrade

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  HashMe37:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HashMe37Call:
          Type: Api
          Properties:
            Path: /hashme37
            Method: get
      Tracing: 'Active'
      Policies:
        - !Ref BucketAccess

  HashMe38:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HashMe38Call:
          Type: Api
          Properties:
            Path: /hashme38
            Method: get
      Tracing: 'Active'
      Policies:
        - !Ref BucketAccess

  BucketAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy that allows to read from the bucket"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:HeadObject
            Resource:
              - 'arn:aws:s3:::lambda-coldstart'
              - 'arn:aws:s3:::lambda-coldstart/*'